from edugym.agents.DynaAgent import DynaAgent
from edugym.agents.DynamicProgrammingAgent import DynamicProgrammingAgent
from edugym.agents.ModelLearningAgent import ModelLearningAgent
from edugym.agents.PrioritizedSweepingAgent import PrioritizedSweepingAgent
from edugym.agents.QLearningAgent import QLearningAgent
from edugym.agents.QLearningAgentDiscretized import DiscretizingQLearningAgent
from edugym.agents.QLearningAgentFrameStacking import QLearningAgent_Framestacking
from edugym.agents.SarsaAgent import SarsaAgent
